name: Tests

on:
  push:
    branches: [main, master, api-refactor]
  pull_request:
    branches: [main, master, api-refactor]

jobs:
  unit:
    name: Unit (Vitest)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install pnpm & deps
        run: |
          npm i -g pnpm
          pnpm install --frozen-lockfile
      - name: Run unit tests
        # adjust if you use a script: e.g. `pnpm test:unit`
        run: pnpm exec vitest run --coverage
      - name: Upload coverage
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 14

  e2e:
    name: E2E (Playwright)
    needs: unit
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install pnpm & deps
        run: |
          npm i -g pnpm
          pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec playwright test
      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
