name: Tests

on:
  push:
    branches: [main, master, infinite-scroll]
  pull_request:
    branches: [main, master, infinite-scroll]

jobs:
  unit:
    name: Unit (Vitest)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      # Install pnpm first so setup-node can cache it
      - uses: pnpm/action-setup@v4
        with:
          version: 9 # or the version in your packageManager field

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm" # now safe; pnpm exists
          cache-dependency-path: |
            pnpm-lock.yaml
            **/pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run unit tests (Vitest)
        run: pnpm exec vitest run

  e2e:
    name: E2E (Playwright)
    needs: unit
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
          cache-dependency-path: |
            pnpm-lock.yaml
            **/pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        env:
          CI: true
        run: pnpm exec playwright test

      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
